<?php
/**
 * @version    $Id$
 * @package    JSN_PageBuilder2
 * @author     JoomlaShine Team <support@joomlashine.com>
 * @copyright  Copyright (C) 2012 JoomlaShine.com. All Rights Reserved.
 * @license    GNU/GPL v2 or later http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Websites: http://www.joomlashine.com
 * Technical Support:  Feedback - http://www.joomlashine.com/contact-us/get-support.html
 */

// No direct access to this file.
defined('_JEXEC') or die('Restricted access');


$base = rtrim(JURI::root(), '/\\');
$base = str_replace(array('https:', 'http:'), '', $base);
// Load script to initialize the editor.

JSNHtmlAsset::loadScript( JURI::root() . 'plugins/editors/pagebuilder2/assets/joomla/hook.js', array(
	'id'        => $displayData->id,
	'rootURL'   => $base,
	'startHTML' => PlgSystemPageBuilder2::$start_html,
	'endHTML'   => PlgSystemPageBuilder2::$end_html,
	'startData' => PlgSystemPageBuilder2::$start_data,
	'endData'   => PlgSystemPageBuilder2::$end_data
) );


// Echo buttons generated by 'editors-xtd' plugins.
// echo $displayData->buttons;

// Only add 'px' to width and height if they are not given as a percentage.
if ( is_numeric( $width ) )
{
	$width .= 'px';
}

if ( is_numeric( $height ) )
{
	$height .= 'px';
}

// Echo the hidden textarea to hold editor data.
?>
<textarea id="<?php echo $displayData->id; ?>" name="<?php echo $displayData->name; ?>" style="display: none;"><?php
	echo $displayData->content;
?></textarea>
